// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: sys_apis_model.proto

package proto

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Symbols defined in public import of google/protobuf/timestamp.proto.

type Timestamp = timestamppb.Timestamp

type SysApis struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @inject_tag: json:"id" gorm:"primary_key;AUTO_INCREMENT;default:;comment:;size:20;"
	Id int64 `protobuf:"varint,100,opt,name=id,proto3" json:"id,omitempty"`
	// @inject_tag: json:"created_at" gorm:"default:;comment:;"
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,101,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// @inject_tag: json:"updated_at" gorm:"default:;comment:;"
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,102,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// @inject_tag: json:"deleted_at" gorm:"default:;comment:;"
	DeletedAt *timestamppb.Timestamp `protobuf:"bytes,103,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	// @inject_tag: json:"path" gorm:"default:api路径;comment:api路径;size:191;"
	Path string `protobuf:"bytes,104,opt,name=path,proto3" json:"path,omitempty"`
	// @inject_tag: json:"description" gorm:"default:api中文描述;comment:api中文描述;size:191;"
	Description string `protobuf:"bytes,105,opt,name=description,proto3" json:"description,omitempty"`
	// @inject_tag: json:"api_group" gorm:"default:api组;comment:api组;size:191;"
	ApiGroup string `protobuf:"bytes,106,opt,name=api_group,json=apiGroup,proto3" json:"api_group,omitempty"`
	// @inject_tag: json:"method" gorm:"default:;comment:;size:191;"
	Method string `protobuf:"bytes,107,opt,name=method,proto3" json:"method,omitempty"`
}

func (x *SysApis) Reset() {
	*x = SysApis{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sys_apis_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SysApis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SysApis) ProtoMessage() {}

func (x *SysApis) ProtoReflect() protoreflect.Message {
	mi := &file_sys_apis_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SysApis.ProtoReflect.Descriptor instead.
func (*SysApis) Descriptor() ([]byte, []int) {
	return file_sys_apis_model_proto_rawDescGZIP(), []int{0}
}

func (x *SysApis) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SysApis) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *SysApis) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *SysApis) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

func (x *SysApis) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *SysApis) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SysApis) GetApiGroup() string {
	if x != nil {
		return x.ApiGroup
	}
	return ""
}

func (x *SysApis) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

var File_sys_apis_model_proto protoreflect.FileDescriptor

var file_sys_apis_model_proto_rawDesc = []byte{
	0x0a, 0x14, 0x73, 0x79, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x73, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x73, 0x79, 0x73, 0x5f, 0x61, 0x70, 0x69, 0x73,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xb5, 0x02, 0x0a, 0x07, 0x53, 0x79, 0x73, 0x41, 0x70, 0x69, 0x73, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x64, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x39, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x65, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x66, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x67, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x68, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x69, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x72, 0x6f, 0x75,
	0x70, 0x18, 0x6a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x70, 0x69, 0x47, 0x72, 0x6f, 0x75,
	0x70, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x6b, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x42, 0x0d, 0x5a, 0x0b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_sys_apis_model_proto_rawDescOnce sync.Once
	file_sys_apis_model_proto_rawDescData = file_sys_apis_model_proto_rawDesc
)

func file_sys_apis_model_proto_rawDescGZIP() []byte {
	file_sys_apis_model_proto_rawDescOnce.Do(func() {
		file_sys_apis_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_sys_apis_model_proto_rawDescData)
	})
	return file_sys_apis_model_proto_rawDescData
}

var file_sys_apis_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_sys_apis_model_proto_goTypes = []interface{}{
	(*SysApis)(nil),               // 0: sys_apis.SysApis
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_sys_apis_model_proto_depIdxs = []int32{
	1, // 0: sys_apis.SysApis.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: sys_apis.SysApis.updated_at:type_name -> google.protobuf.Timestamp
	1, // 2: sys_apis.SysApis.deleted_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_sys_apis_model_proto_init() }
func file_sys_apis_model_proto_init() {
	if File_sys_apis_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sys_apis_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SysApis); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sys_apis_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_sys_apis_model_proto_goTypes,
		DependencyIndexes: file_sys_apis_model_proto_depIdxs,
		MessageInfos:      file_sys_apis_model_proto_msgTypes,
	}.Build()
	File_sys_apis_model_proto = out.File
	file_sys_apis_model_proto_rawDesc = nil
	file_sys_apis_model_proto_goTypes = nil
	file_sys_apis_model_proto_depIdxs = nil
}
